config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get   'signup'  =>  'users#new'

  get   'signin'  =>  'auth#new'
  post  'signin'  =>  'auth#create'

  get   'signin/:token'   =>  'auth#update'
  get   'signout'         =>  'auth#destroy'

  post  'users'   =>  'users#create'
end

app/models/access_token.rb
class AccessToken < BaseToken
  expire_after 30.days

  self.table_name = :access_tokens

  def self.from_auth_token(auth_token)
    auth_token.expire!
    @access_token = AccessToken.new(user: auth_token.user)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth_token.rb
class AuthToken < BaseToken
  expire_after 10.minutes

  self.table_name = :auth_tokens

  after_create :send_signin_link

  def send_signin_link
    AuthMailer.generate_signin_link(self).deliver_now
  end
end

app/models/base_token.rb
class BaseToken < ApplicationRecord
  class << self
    attr_accessor :expires_after
  end

  self.expires_after = 1.day if self.expires_after.blank?

  self.abstract_class = true

  def self.expire_after(period)
    self.expires_after = period
  end

  belongs_to :user

  has_secure_token :token

  before_create :set_expires_at

  delegate :email, to: :user

  scope :active, -> { where('expires_at > ?', Time.now) }

  def set_expires_at
    self.expires_at = Time.now + self.class.expires_after
  end

  def expired?
    self.expires_at < Time.now
  end

  def expire!
    self.update(expires_at: Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :access_tokens, dependent: :destroy
  has_many :auth_tokens, dependent: :destroy

  after_create :generate_auth_token

  validates :email, presence: true, uniqueness: true

  def generate_auth_token
    AuthToken.create(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authenticate
    if current_user.nil?
      flash[:notice] = 'You must be sigined in to do that'
      redirect_to signup_url
    end
  end

  def current_access_token
    token = cookies.permanent.signed[:access_token]
    if token
      @current_access_token = AccessToken.where(token: token).first
    end
  end

  def current_user
    if current_access_token
      @current_user = User.find(@current_access_token.user_id)
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :set_auth_token, only: :update

  def new
  end

  def create
    if params[:email]
      @user = User.where(email: params[:email]).first
    else
      flash[:notice] = 'Missing param: email'
      return render :new
    end

    @auth_token = AuthToken.new(user: @user)
    if @auth_token.save
      flash[:notice] = 'You will receive a signin link shortly, thanks for being patient!'
      redirect_to root_url
    else
      flash[:notice] = 'There was a problem delivering your signin link, please try again'
      render :new
    end
  end

  def update
    @access_token = AccessToken.from_auth_token(@auth_token)
    if @access_token.save
      flash[:notice] = 'Welcome! You are all signed in'
      cookies.permanent.signed[:access_token] = @access_token.token
      redirect_to root_url
    else
      flash[:notice] = 'Oops there was an error generating your access token. Please try again'
      render :new
    end
  end

  def destroy
    @access_token = current_access_token
    cookies.delete(:access_token)
    if @access_token.expire!
      flash[:notice] = 'Successfully logged out!'
      redirect_to root_url
    else
      flash[:notice] = 'There was an error signing you out'
      redirect_to :back
    end
  end

  private

  def set_auth_token
    if !params[:token]
      raise ActionController::RoutingError.new('Not Found')
    end

    @auth_token = AuthToken.where(token: params[:token]).first
    if !@auth_token
      raise ActionController::RoutingError.new('Not Found')
    elsif @auth_token.expired?
      flash[:notice] = 'Token has expired. Please request a new signin link'
      redirect_to signin_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'You will receive a signin link shortly, thanks for being patient!'
      redirect_to root_url
    else
      flash[:notice] = 'Oops there was an error signing you up'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :current_user

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veranda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="<%= name %>">
        <p><%= msg %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br><br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <p>Please enter your email to signup!<br>Then you'll receive a link to sign in.</p>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.submit 'Signup' %>
<% end %>

app/views/welcome/index.html.erb
<% if @current_user %>
<h1>Welcome to the world of passwordless authentication, <%= @current_user.name || 'Friend' %>!</h1>
From here, you can:
<ul>
  <li><%= link_to 'Request a new signin link', signin_path %></li>
  <li><%= link_to 'or Signout', signout_path %></li>
</ul>
<% else %>
  <h1>Welcome to the world of passwordless authentication, Friend!</h1>
  From here, you can:
  <ul>
    <li><%= link_to 'Signup for a test drive', signup_url %></li>
    <li><%= link_to 'Or signin if you have an account', signin_path %>
  </ul>
<% end %>